name: Workflow Dispatch Example

on:
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set RELEASE_TAG as an environment variable
        run: |
          echo "RELEASE_TAG=${{ env.RELEASE_TAG }}" >> $GITHUB_ENV
      
      - name: Get release info for ref
        id: release
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.RELEASE_TAG }})
          RELEASE_TAG=$(echo $RELEASE_INFO | jq -r '.tag_name')
          echo "::set-output name=tag::$RELEASE_TAG"
      
      - name: Compare ref and release
        if: steps.release.outputs.tag != env.RELEASE_TAG
        run: |
          echo "Error: The ref you selected does not have a release associated with it. Please select a ref from the releases."
          exit 1
      
      - name: Continue with the workflow
        run: |
          echo "The ref you selected has a release associated with it. Proceeding with the workflow."
