name: Your Workflow Name
on:
  workflow_dispatch:
    inputs:
      ref_tag:
        description: 'Tag to use for the workflow'
        required: true

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if release exists for the tag
        run: |
          TAG_NAME="${{ github.event.inputs.ref_tag }}"
          RELEASE=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME)
          if [[ -z "$RELEASE" ]]; then
            echo "Error: No release found for tag $TAG_NAME. Please select a tag from the releases."
            exit 1
          fi
