name: Manual Tag Trigger Workflow

on:
  workflow_dispatch

jobs:
  check_release_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: check for a tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/"* ]]; then
          echo "Deployment failure. This is a PROD CD you can only proceed using released tags for successful deployment"
          exit 1
          fi
        
      - name: get releases
        working-directory: /home/runner/work/cd_only_on_release_tags/.github/workflows
        run: |
        
          ll
          pwd
          
          chmod +x get_release.sh
          ./get_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CD
        run: |
          echo "CD is complete"

  


