name: Manual Tag Trigger Workflow

on:
  workflow_dispatch

jobs:
  check_release_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run migrations
        run: sh ./github/scripts/migrate.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        
      - name: get releases
        run: |
          chmod +x get_release.sh
          ./get_release.sh

      - name: CD
        run: |
          echo "CD is complete"


