name: Check Release Workflow
on:
  workflow_dispatch
    # inputs:
    #   ref_tag:
    #     description: 'Tag to use for the workflow'
    #     required: true

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Check if release exists for the tag
        id: check_release
        run: |
          TAG_NAME="${{ github.event.inputs.ref_tag }}"
          echo $TAG_NAME
          RELEASES=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/releases)
          echo $RELEASES
          MATCH=$(echo "$RELEASES" | jq -r ".[] | select(.tag_name == \"$TAG_NAME\") | .id")
          echo $MATCH
          if [ -z "$MATCH" ]; then
            echo "Error: No release found for tag $TAG_NAME. Please select a tag from the releases."
            exit 1
          fi
