name: Manual Tag Trigger Workflow

on:
  workflow_dispatch

jobs:
  check_release_job:
    if: GITHUB_REF == "refs/tags/*"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: get releases
        run: |
          chmod +x get_release.sh
          ./get_release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CD
        run: |
          echo "CD is complete"

  build_on_branch:
    runs-on: ubuntu-latest
    if: GITHUB_REF == "refs/heads/*"

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: failure message
      run: echo "Deployment failure. This is a PROD CD you can only proceed using released tags for successful deployment"


